name: sort.py

on:
  push:
    branches: [ master ]
    paths:
      - 'etc/**'
      - 'contrib/sort.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'etc/**'
      - 'contrib/sort.py'

jobs:
  profile-sort:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: check profiles
      run: ./contrib/sort.py etc/*/{*.inc,*.profile}

